### ISSUE TITLE
api/kilkari - Save Inbox Call Details

### ISSUE THREAD

**Issue by llavoie** [koshalt/mim#12]

**Comment by frankhuster** [comment]
Need to make kilkari service call for this API to be complete.
@larubbio should the Kilkari inbox CallDetails be handles by the FLW module or the Kilkari module?
Seems to me that Kilkari is the right place, but I may be wrong.

**Comment by larubbio** [comment]
Depends on the functionality.  If the data being loaded is the same then it
should live in the same module and then we'll have to rename things.  If it
is different then kilkari would be the right place.

**Comment by larubbio** [comment]
Looking at the spec, it returns the users language if known.  If not the
default.  That is in common with the flw get user api.  However it does not
do any of the service usage logic and instead has it's own subscription
logic.

So I would put it in the kilkari module and keep it separate.

**Comment by frankhuster** [comment]
roger

On Fri, Apr 24, 2015 at 3:02 PM, Rob LaRubbio <notifications@github.com>
wrote:

> Looking at the spec, it returns the users language if known. If not the
> default. That is in common with the flw get user api. However it does not
> do any of the service usage logic and instead has it's own subscription
> logic.
>
> So I would put it in the kilkari module and keep it separate.
>
>
> On Fri, Apr 24, 2015 at 3:00 PM, Rob LaRubbio <rob@larubbio.org> wrote:
>
> > Depends on the functionality. If the data being loaded is the same then
> > it should live in the same module and then we'll have to rename things.
> If
> > it is different then kilkari would be the right place.
> >
> >
> > On Fri, Apr 24, 2015 at 2:59 PM, Frank Huster <notifications@github.com>
> > wrote:
> >
> >> Need to make kilkari service call for this API to be complete.
> >> @larubbio <https://github.com/larubbio> should the Kilkari inbox
> >> CallDetails be handles by the FLW module or the Kilkari module?
> >> Seems to me that Kilkari is the right place, but I may be wrong.
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <https://github.com/koshalt/mim/issues/12#issuecomment-96078768>.
>
> >>
> >
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/koshalt/mim/issues/12#issuecomment-96079323>.
>



-- 
Frank Huster
Mobile Health Innovations
Grameen Foundation
+1.206.325.6690 x201

**Comment by frankhuster** [comment]
For the content part of the CallDetail, the spec says
>List of call details. For promotional message this field shall not be present.

What does that mean?

**Comment by larubbio** [comment]
Under certain conditions* the IVR will play the user a promotional
message.  The content array will contain messages played to the user, but
not the promotional message.  So if only the promo message was played the
the content field will not be included.

*One case is when inboxSubscriptionDetailList is not returned in the
getinbox api (I just reopened #9 to cover and test this case.)
