### ISSUE TITLE
In api/BaseController log when an internal error is returned

### ISSUE THREAD

**Issue by larubbio** [koshalt/mim#42]

**Comment by larubbio** [comment]
I had this code but it was running for all exceptions


    @ExceptionHandler(Exception.class)
    @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
    @ResponseBody
    public BadRequest handleException(Exception e) throws IOException {
        // TODO: Log internal error
        return new BadRequest("Internal Error");
    }

**Comment by frankhuster** [comment]
Define "internal error" ;-)

I think the code above catches exceptions of type Exception (which is all of them) and returns 500.
So, for example, if we know that an uncaught NPE is something that would constitute an internal error, then we'd want something like:
```
@ExceptionHandler(NullPointerException.class) 
```

I guess I can add that as a start and we can build up on it as we go...

**Comment by frankhuster** [comment]
We'll still need to find a way to test that.
