### ISSUE TITLE
api in call details add correctAnswerEntered

### ISSUE THREAD

**Issue by larubbio** [koshalt/mim#84]
Section 2.2.6: A new field is added in “Save CallDetails API” (MA) to get the information whether a particular question is correctly answered or not. This is needed for a MA report.

callData>>correctAnswerEntered	Not required	Boolean		
true – question answered correctly by user
false – question not answered correctly by the user		

The field is relevant only if content type is ‘question’ and completionFlag is ‘true’ for the question. 

It specifies whether the user has answered the question correctly or not. 
If the user has not attempted the question then IVR need not send this field.

**Comment by frankhuster** [comment]
Fixed in pull request #86
