### ISSUE TITLE
kilkari.UserResponse.subscriptionPackList should be List<String> instead of Set<String>

### ISSUE THREAD

**Issue by frankhuster** [koshalt/mim#89]
4.2.1.2 Get Subscriber Details API – Response

**Comment by larubbio** [comment]
Does it have to be?  I think it is serialized to json the same way, I thought the only difference on the server was that list provided a guaranteed order while set does not.

**Comment by frankhuster** [comment]
It doesn't have to.
subscriptionPackList suggests a list, not a set.
So it should.

On Fri, Apr 24, 2015 at 10:49 AM, Rob LaRubbio <notifications@github.com>
wrote:

> Does it have to be? I think it is serialized to json the same way, I
> thought the only difference on the server was that list provided a
> guaranteed order while set does not.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/koshalt/mim/issues/89#issuecomment-96011247>.
>



-- 
Frank Huster
Mobile Health Innovations
Grameen Foundation
+1.206.325.6690 x201

**Comment by larubbio** [comment]
I agree, but I think to use a List you have to provide a sort column, and
there isn't a natural one for that table.  In this case I would suggest
just leaving it as is.

**Comment by frankhuster** [comment]
You don't really have to use a sort column, but you may want to sort you
results if you care about consistency in the resulting List.
But no biggie.
Is it worth pushing to rename subscriptionPackList to subscriptionPackSet?
Or shall I just be quiet and drop the issue altogether?

On Fri, Apr 24, 2015 at 1:48 PM, Rob LaRubbio <notifications@github.com>
wrote:

> I agree, but I think to use a List you have to provide a sort column, and
> there isn't a natural one for that table. In this case I would suggest
> just leaving it as is.
>
>
> On Fri, Apr 24, 2015 at 11:41 AM, Frank Huster <notifications@github.com>
> wrote:
>
> > It doesn't have to.
> > subscriptionPackList suggests a list, not a set.
> > So it should.
> >
> > On Fri, Apr 24, 2015 at 10:49 AM, Rob LaRubbio <notifications@github.com
> >
> > wrote:
> >
> > > Does it have to be? I think it is serialized to json the same way, I
> > > thought the only difference on the server was that list provided a
> > > guaranteed order while set does not.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/koshalt/mim/issues/89#issuecomment-96011247>.
> > >
> >
> >
> >
> > --
> > Frank Huster
> > Mobile Health Innovations
> > Grameen Foundation
> > +1.206.325.6690 x201
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/koshalt/mim/issues/89#issuecomment-96029231>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/koshalt/mim/issues/89#issuecomment-96061201>.
>



-- 
Frank Huster
Mobile Health Innovations
Grameen Foundation
+1.206.325.6690 x201

**Comment by larubbio** [comment]
If you don't need a sort column and it is just a type change then go ahead
an make the switch.  I thought there was more work involved.  My only
concern would be that there is no actual ordering so using an ordered type
implies something that may not be true (I did make this change for the call
detail records since there was an actual order).  I'm not willing to push
for the name change, it seems like it may be viewed as ... I can't actually
explain my concern there.

**Comment by llavoie** [comment]
I agree that the name change is not worth pushing for. From IMI's
perspective, they don't care that "list" implies ordered in Java -- they
just mean a group of things. The API doc also doesn't say anything about
whether the packs are ordered or not, so I just assumed it doesn't matter.
I'm not opposed to the change, but it's not clear to me what value it adds.

On Fri, Apr 24, 2015 at 2:03 PM, Rob LaRubbio <notifications@github.com>
wrote:

> If you don't need a sort column and it is just a type change then go ahead
> an make the switch. I thought there was more work involved. My only
> concern would be that there is no actual ordering so using an ordered type
> implies something that may not be true (I did make this change for the call
> detail records since there was an actual order). I'm not willing to push
> for the name change, it seems like it may be viewed as ... I can't actually
> explain my concern there.
>
> On Fri, Apr 24, 2015 at 1:53 PM, Frank Huster <notifications@github.com>
> wrote:
>
>
> > You don't really have to use a sort column, but you may want to sort you
> > results if you care about consistency in the resulting List.
> > But no biggie.
> > Is it worth pushing to rename subscriptionPackList to
> subscriptionPackSet?
> > Or shall I just be quiet and drop the issue altogether?
> >
> > On Fri, Apr 24, 2015 at 1:48 PM, Rob LaRubbio <notifications@github.com>
> > wrote:
> >
> >
> > > I agree, but I think to use a List you have to provide a sort column,
> and
> > > there isn't a natural one for that table. In this case I would suggest
> > > just leaving it as is.
> > >
> > >
> > > On Fri, Apr 24, 2015 at 11:41 AM, Frank Huster <
> notifications@github.com
> > >
> > > wrote:
> > >
> > > > It doesn't have to.
> > > > subscriptionPackList suggests a list, not a set.
> > > > So it should.
> > > >
> > > > On Fri, Apr 24, 2015 at 10:49 AM, Rob LaRubbio <
> > notifications@github.com
> > > >
> > > > wrote:
> > > >
> > > > > Does it have to be? I think it is serialized to json the same way,
> I
> > > > > thought the only difference on the server was that list provided a
> > > > > guaranteed order while set does not.
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <https://github.com/koshalt/mim/issues/89#issuecomment-96011247>.
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > Frank Huster
> > > > Mobile Health Innovations
> > > > Grameen Foundation
> > > > +1.206.325.6690 x201
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/koshalt/mim/issues/89#issuecomment-96029231>.
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/koshalt/mim/issues/89#issuecomment-96061201>.
> > >
> >
> >
> >
> > --
> > Frank Huster
> > Mobile Health Innovations
> > Grameen Foundation
> > +1.206.325.6690 x201
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/koshalt/mim/issues/89#issuecomment-96062282>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/koshalt/mim/issues/89#issuecomment-96064204>.
>



-- 
Lauren Lavoie
Software Development Manager, Mobile Health Innovations
Grameen Foundation
2101 4th Ave | Suite 1550 | Seattle, WA 98121
206-325-6690 ext 254
llavoie@grameenfoundation.org | Skype:laurenlavoie
Facebook <http://www.facebook.com/StopPovertyNow>│Twitter
<http://twitter.com/grameenfdn>│YouTube
<http://www.youtube.com/user/grameen?blend=6&ob=5> | www.motechsuite.org
*Connecting the World's Poor to Their Potential*

**Comment by frankhuster** [comment]
@llavoie:
> it's not clear to me what value it adds

@larubbio:
> I can't actually explain my concern there.

I'll just drop it.
