### ISSUE TITLE
api/kilkari - Get Inbox Details

### ISSUE THREAD

**Issue by llavoie** [koshalt/mim#9]

**Comment by larubbio** [comment]
I think we need a test for a valid subscriber with no inbox messages.  Or change our response if the subscriber is not found.  Currently we return 400.  I think we should instead return:

```javascript
{
  "inboxSubscriptionDetailList": []
}
```
According to the spec:

List of details of subscriptions having inbox.
If not present then IVR shall play promotional message.

Also the ivr checks like this:

```xml
   <if cond="lRespInboxDetailsObject.inboxSubscriptionDetailList.length &lt;= 0" >
      <log> No Messages Available </log>
      <goto next="#PromoMsg"/>
   </if>
```

**Comment by frankhuster** [comment]
As of now, it looks like the code already returns an empty set:
```java
        Subscriber subscriber = kilkariService.getSubscriber(callingNumber);
        if (subscriber == null) {
            throw new NotFoundException(String.format(NOT_FOUND, "callingNumber"));
        }

        Set<Subscription> subscriptions = subscriber.getSubscriptions();
        Set<InboxSubscriptionDetailResponse> subscriptionDetails = new HashSet<>();
        for (Subscription subscription : subscriptions) {
            subscriptionDetails.add(new InboxSubscriptionDetailResponse(subscription.getSubscriptionId(),
                    subscription.getSubscriptionPack().getName(),
                    "10_1",
                    "xyz.wav"));
        }
```

Granted it's a bit hard-coded, but the spirit is right.
Should we close that until Sprint2?

**Comment by larubbio** [comment]
It's the if check above.

If subscriber == null I think we should return. 200 with an empty
subscriptions list

**Comment by frankhuster** [comment]
I'll look into it.
To tell @llavoie I'm taking over I'm assigning it to me, right?

**Comment by frankhuster** [comment]
If ```kilkariService.getSubscriber(callingNumber)``` returns ```null``` it means there is no such subscriber in the database. It doesn't mean there is a valid subscriber with no subscription details. Am I missing something @larubbio ?

**Comment by larubbio** [comment]
Correct, but if you look at the API spec this is the return values for
successful are:

```
{
    "circle": "AP",
    "languageLocationCode": “10”,
    "subscriptionPackList": [
        "48WeeksPack",
        "72WeeksPack"
    ]
}

Or

{
"circle": "AP",
    "defaultLanguageLocationCode": “10”
}

Or

{
"circle": "99",
    "defaultLanguageLocationCode": “10”
}
```

The last two are the case were there is no subscriber in the database.  I
think the vxml code checks the length of subscriptionPackList so it is ok
if we return it as an empty array.  Actually it has to be returned or the
vxml will error:

```xml
   <!-- check if any messages available -->
   <if cond="lRespInboxDetailsObject.inboxSubscriptionDetailList.length
&lt;= 0" >
     <log> No Messages Available </log>
     <goto next="#PromoMsg"/>
   </if>
```

  We should amend the spec to show that though.

This way if a user calls kilkari inbox and they aren't already subscribed
they will hear a promo msg and then (I think) have the option to
subscribe.  If we return 400 the IVR will just hang up.
​

**Comment by larubbio** [comment]
Correct, but if you look at the API spec this is the return values for
successful are:

```
{
    "circle": "AP",
    "languageLocationCode": “10”,
    "subscriptionPackList": [
        "48WeeksPack",
        "72WeeksPack"
    ]
}

Or

{
"circle": "AP",
    "defaultLanguageLocationCode": “10”
}

Or

{
"circle": "99",
    "defaultLanguageLocationCode": “10”
}
```

The last two are the case were there is no subscriber in the database.  I
think the vxml code checks the length of subscriptionPackList so it is ok
if we return it as an empty array.  Actually it has to be returned or the
vxml will error:

```xml
   <!-- check if any messages available -->
   <if cond="lRespInboxDetailsObject.inboxSubscriptionDetailList.length
&lt;= 0" >
     <log> No Messages Available </log>
     <goto next="#PromoMsg"/>
   </if>
```
 We should amend the spec to show that though.

This way if a user calls kilkari inbox and they aren't already subscribed
they will hear a promo msg and then (I think) have the option to
subscribe.  If we return 400 the IVR will just hang up.
​

**Comment by frankhuster** [comment]
OK got it, so we return a ```KilkariUserResponse``` object (which doesn't correspond to a database record) with an empty ``subscriptionPackList``` member and all the other values in the response body identical to that which were supplied in the request?

**Comment by frankhuster** [comment]
I just realized there's a bit of confusion here. This issue is about getInboxDetails, but I think you're talking about getUserDetails for the kilkari module. So the branch & pull request numbers (#9) will be a bit misleading. Can you confirm you understand & agree @larubbio?

**Comment by frankhuster** [comment]
And to complicate things further, I also just realized that languageLocationCode was added to the getInboxDetails API (not the API @larubbio was actually talking about, that one is getUserDetails) so I'm adding that too...

**Comment by frankhuster** [comment]
In what circumstances does /kilkari/user return
```json
{
   "circle": "AP",
   "defaultLanguageLocationCode": "10"
}
```
and
```json
{
   "circle": "99",
   "defaultLanguageLocationCode": "10"
}
```
the fog thickens...

**Comment by llavoie** [comment]
Thanks for looking at this, Frankie.

On Sat, Apr 25, 2015 at 12:26 PM, Frank Huster <notifications@github.com>
wrote:

> In what circumstances does /kilkari/user return
>
> {
>    "circle": "AP",
>    "defaultLanguageLocationCode": "10"
> }
>
> and
>
> {
>    "circle": "99",
>    "defaultLanguageLocationCode": "10"
> }
>
> the fog thickens...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/koshalt/mim/issues/9#issuecomment-96267123>.
>



-- 
Lauren Lavoie
Software Development Manager, Mobile Health Innovations
Grameen Foundation
2101 4th Ave | Suite 1550 | Seattle, WA 98121
206-325-6690 ext 254
llavoie@grameenfoundation.org | Skype:laurenlavoie
Facebook <http://www.facebook.com/StopPovertyNow>│Twitter
<http://twitter.com/grameenfdn>│YouTube
<http://www.youtube.com/user/grameen?blend=6&ob=5> | www.motechsuite.org
*Connecting the World's Poor to Their Potential*

**Comment by larubbio** [comment]
I am confused.  I think the code for get inbox details is correct.  It should only be called with a valid user.

I think the code for get user is incorrect.  A user is able to subscribe by calling the IVR, so that method can't throw a 400 if no user is found.  So to answer your question @frankhuster those two returns would be the case where a new user calls kilkari.

**Comment by larubbio** [comment]
So in summary I think this ticket can be re-closed and the one for kilkari get user is the one I should have reopened.

**Comment by frankhuster** [comment]
Yeah, understood. I'll close this ticket & re-open /kilkari/user
